import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, Image, ScrollView, Alert } from 'react-native';

export default function App() {
  const [mobile, setMobile] = useState('');
    const [otp, setOtp] = useState('');
      const [loggedIn, setLoggedIn] = useState(false);
        const [showOtp, setShowOtp] = useState(false);

          const handleLogin = () => {
              if (mobile.length !== 10) {
                    Alert.alert('RPI', '10 digit mobile number likho Papa Ji');
                          return;
                              }
                                  setShowOtp(true);
                                      Alert.alert('OTP Bheja Gaya', 'OTP: 123456');
                                        };

                                          const verifyOtp = () => {
                                              if (otp === '123456') setLoggedIn(true);
                                                  else Alert.alert('Galat OTP', 'Sahi OTP 123456 hai');
                                                    };

                                                      if (loggedIn) {
                                                          return (
                                                                <View style={styles.containerGold}>
                                                                        <View style={styles.goldCard}>
                                                                                  <Image 
                                                                                              source={{ uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/B_R_Ambedkar.jpg/440px-B_R_Ambedkar.jpg' }}
                                                                                                          style={styles.babaPhoto}
                                                                                                                    />
                                                                                                                              <Text style={styles.title}>RPI - BA BABA SAHEB</Text>
                                                                                                                                        <Text style={styles.subTitle}>Republican Party of India</Text>
                                                                                                                                                  <View style={styles.divider} />
                                                                                                                                                            <Text style={styles.label}>Member ID</Text>
                                                                                                                                                                      <Text style={styles.memberId}>MHBA10000000001</Text>
                                                                                                                                                                                <Text style={styles.label}>Name</Text>
                                                                                                                                                                                          <Text style={styles.value}>Haripreet Rpsingh Shergarh</Text>
                                                                                                                                                                                                    <Text style={styles.label}>Mobile</Text>
                                                                                                                                                                                                              <Text style={styles.value}>{mobile}</Text>
                                                                                                                                                                                                                        <Text style={styles.jaiBhim}>JAI BHIM! JAI BHARAT!</Text>
                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                        <TouchableOpacity style={styles.logoutBtn} onPress={() => setLoggedIn(false)}>
                                                                                                                                                                                                                                                  <Text style={styles.logoutText}>Logout</Text>
                                                                                                                                                                                                                                                          </TouchableOpacity>
                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                            <ScrollView contentContainerStyle={styles.container}>
                                                                                                                                                                                                                                                                                  <Text style={styles.header}>RPI</Text>
                                                                                                                                                                                                                                                                                        <Text style={styles.header2}>BA BABA SAHEB</Text>
                                                                                                                                                                                                                                                                                              <Text style={styles.tagline}>Dr. B. R. Ambedkar Mission</Text>
                                                                                                                                                                                                                                                                                                    <View style={styles.inputBox}>
                                                                                                                                                                                                                                                                                                            <Text style={styles.inputLabel}>Mobile Number</Text>
                                                                                                                                                                                                                                                                                                                    <TextInput style={styles.input} placeholder="9876543210" keyboardType="number-pad" maxLength={10} value={mobile} onChangeText={setMobile} />
                                                                                                                                                                                                                                                                                                                            {showOtp && (
                                                                                                                                                                                                                                                                                                                                      <>
                                                                                                                                                                                                                                                                                                                                                  <Text style={styles.inputLabel}>OTP (123456)</Text>
                                                                                                                                                                                                                                                                                                                                                              <TextInput style={styles.input} placeholder="123456" keyboardType="number-pad" maxLength={6} value={otp} onChangeText={setOtp} />
                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                        {!showOtp ? (
                                                                                                                                                                                                                                                                                                                                                                                                  <TouchableOpacity style={styles.btn} onPress={handleLogin}><Text style={styles.btnText}>Send OTP</Text></TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                    <TouchableOpacity style={[styles.btn, { backgroundColor: '#FFD700' }]} onPress={verifyOtp}><Text style={[styles.btnText, { color: '#0D47A1' }]}>Verify & Login</Text></TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                  </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <Text style={styles.footer}>Package: com.celestials.rpi.ba | SDK v55.0.0 Safe</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                              const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                container: { flexGrow: 1, backgroundColor: '#0D47A1', alignItems: 'center', padding: 20, paddingTop: 60 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                  containerGold: { flex: 1, backgroundColor: '#0D47A1', alignItems: 'center', justifyContent: 'center', padding: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                    header: { fontSize: 48, fontWeight: 'bold', color: '#FFD700', marginTop: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                      header2: { fontSize: 22, fontWeight: 'bold', color: 'white', letterSpacing: 2 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                        tagline: { color: 'white', marginBottom: 30, opacity: 0.9 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                          inputBox: { backgroundColor: 'white', width: '100%', borderRadius: 15, padding: 20, elevation: 5 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                            inputLabel: { fontWeight: 'bold', color: '#0D47A1', marginTop: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                              input: { borderWidth: 1, borderColor: '#0D47A1', borderRadius: 8, padding: 12, marginTop: 5, fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                btn: { backgroundColor: '#0D47A1', padding: 15, borderRadius: 10, alignItems: 'center', marginTop: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  btnText: { color: 'white', fontWeight: 'bold', fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    goldCard: { backgroundColor: '#FFD700', width: '100%', borderRadius: 20, padding: 25, alignItems: 'center', borderWidth: 4, borderColor: 'white', elevation: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      babaPhoto: { width: 130, height: 130, borderRadius: 65, borderWidth: 3, borderColor: '#0D47A1', marginBottom: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title: { fontSize: 20, fontWeight: 'bold', color: '#0D47A1' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          subTitle: { color: '#0D47A1', fontWeight: '600', marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            divider: { height: 2, backgroundColor: '#0D47A1', width: '100%', marginVertical: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              label: { fontSize: 12, color: '#0D47A1', marginTop: 10, opacity: 0.7 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                memberId: { fontSize: 20, fontWeight: 'bold', color: '#0D47A1' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value: { fontSize: 16, fontWeight: 'bold', color: '#000' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    jaiBhim: { marginTop: 20, fontWeight: 'bold', color: '#0D47A1', fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      logoutBtn: { marginTop: 20, backgroundColor: 'white', padding: 12, borderRadius: 8, paddingHorizontal: 30 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logoutText: { color: '#0D47A1', fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          footer: { color: 'white', fontSize: 10, marginTop: 20, opacity: 0.6 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });